name: windows

on:
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest
    continue-on-error: false
    strategy:
      fail-fast: false
      matrix:
        php: ['8.0', '8.1', '8.2', '8.3']
        ts: [nts, ts]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: GmSSL-v3

      - name: Build
        # Build your program with the given configuration
        run: |
          mkdir build
          cd build
          cmake ..
          make
          make install
          
      - name: Install PHP ${{ matrix.php }}
        uses: php/setup-php-sdk@v0.10
        id: setup-php-sdk
        with:
          version: ${{ matrix.php }}
          arch: x64
          ts: ${{matrix.ts}}
          cache: true

      - name: Install dependencies
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
          toolset: ${{steps.setup-php-sdk.outputs.toolset}}

      - name: Checkout tools repo
        uses: actions/checkout@v4
        with:
          repository: GmTLS/GmSSL-PHP
          path: GmSSL-PHP

      - name: Build phpredis
        run: |
          phpize
          ./configure
          nmake
          tree

      # - name: Upload artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: redis-${{matrix.php}}-x64-${{matrix.ts}}
      #     path: binaries
