name: windows

on:
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  windows:
    runs-on: windows-latest
    continue-on-error: false
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.3']
        ts: [nts, ts]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: GmSSL-v3
      - name: Install dependencies
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
          toolset: ${{steps.setup-php-sdk.outputs.toolset}}
      - name: Configure CMake
        # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
        # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
        run: cmake -B ${{github.workspace}}\build -G "NMake Makefiles";
      - name: Build
        working-directory: ${{github.workspace}}\build
        # Build your program with the given configuration
        run: nmake
      - name: Checkout tools repo
        uses: actions/checkout@v4
        with:
          repository: GmTLS/GmSSL-PHP
          path: ${{github.workspace}}/GmSSL-PHP
      - name: Install PHP ${{ matrix.php }}
        uses: php/setup-php-sdk@v0.10
        id: setup-php-sdk
        with:
          version: ${{ matrix.php }}
          arch: x64
          ts: ${{matrix.ts}}
          cache: true
      - name: Build phpredis
        env:
          PATH: ${{github.workspace}}\build\bin;%PATH%
        run: |
          phpize
          ./configure --enable-gmssl --with-prefix=${{steps.setup-php-sdk.outputs.prefix}}
          nmake
          tree
      # - name: Upload artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: redis-${{matrix.php}}-x64-${{matrix.ts}}
      #     path: binaries
